### ISSUE TITLE
Open Folder in Explorer

### ISSUE THREAD

**Issue by universal** [GAMS-dev/studio#127]
Hello,

I personally would find it really helpful to be able to open a folder in the explorer, and see all files inside that folder and be able to quickly open files from there. Similar to the Project Pane in sublime/atom/textmate/... .

In this regard a "go-to" file functionality might also be helpful, with partial matching to the path and filename, also inspired by what is available in text editors like sublime/atom/textmate/... .

This is very much driven by my personal style of organizing the code and I usually have my code split accross multiple files, since I find it really hard to navigate and handle files with hundreds/thousands lines of code.

**Comment by MrMontag** [comment]
Hi,

thank you for your feature request. I will take a look at the feature and check how it could be integrated.

**Comment by LutzWestermann** [comment]
@universal , with Studio 1.8 we did a bigger rework of the Project Explorer, so that it shows now the folder structure of files added to a project. We know, that this is not all you were asking for, but at least goes into that direction.

For the next steps may I ask: Would it help you more to add an "add folder" option, that adds a whole folder to a project including all files which exist in that folder at that moment, or do you want to see the whole file system representation wit all future changes? So the difference would be to update the view, whenever a file gets added to a folder externally or not.

**Comment by universal** [comment]
@LutzWestermann this sounds great! I will have a look when time permits.

For me personally, I think adding a(the) folder to a project, seeing the files in there (like in sublime/vs code/...) would be nice, as this does not require opening files from the "file chooser". Seeing also updates like added files automatically would be a nice quality of life feature. 

Given one can control+click $include files to open them, this is not really urgent to me.

**Comment by LutzWestermann** [comment]
@universal , with the [latest release](https://github.com/GAMS-dev/studio/releases/tag/v1.11.0), we added the option to add a whole folder to a project or as a new project in Studio (aka. all files in that folder). This is available via `File -> Open Folder`. Alternatively, you could use drag'n'drop from outside Studio to add a folder.

This Studio release is planned to be published with the upcoming GAMS 40 release.

**Comment by rgoltermann** [comment]
We are happy to announce that the requested go-to feature made it into the [latest version of Studio](https://github.com/GAMS-dev/studio/releases/tag/v1.12.1). It's called Navigator and can be accessed by pressing Ctrl+K.
