### ISSUE TITLE
Ubuntu 18.04: Shift+Arrow-Keys does not work

### ISSUE THREAD

**Issue by universal** [GAMS-dev/studio#191]
Hello,

i just installed the latest 31.0 beta release and noticed that in the Studio editor I can no longer mark text by holding down shift and moving the cursor by the arrow keys. The same error happens for me with 31.3, though not with the Studio version from 27.2. 

Additionally on my home-machine, also Ubuntu 18.04., the numpad does not work for number input, but seems to be stuck in "arrow"-mode. 

I hope this is somewhat understandable, if I can provide any more input, I'd be happy to :-)

**Comment by rgoltermann** [comment]
hello and thank you for your feedback.
we are aware of this issue and are still trying to understand what causes it. in the past it appeared for us on the Fedora distribution but disappeared recently. we suspect this issue is related to AppImages and the operating system.  
if we have more information about what causes this or how to fix it we will notify you here.  

In the meantime, one possibility would be to build studio for yourself: [Instructions](https://github.com/GAMS-dev/studio#how-to-build). For us the issue did not occur in compiled versions of Studio, we understand however that this solution is not feasible for all users.

**Comment by MrMontag** [comment]
@universal, the issue has been found and will be fixed with the new next Studio release, which is planned for the 15th of May.

**Comment by universal** [comment]
cool :-) looking forward to it. thanks for all the work

**Comment by MrMontag** [comment]
@universal In Studio 1.1.1 this issues is fixed.
